---
title: '`audio_spinner`'
subtitle: Create an audio spinner

---

## Description

Create an audio spinner

## Usage

``` R
audio_spinner(
  ...,
  src = NULL,
  con = NULL,
  rpm = 10,
  gap = pi/5,
  stroke = 2.5,
  min_radius = 30,
  radius_compression = 0.8,
  radius_overscan = 1.1,
  steps = 2,
  blades = 3,
  width = "125px",
  height = "125px",
  autoplay = TRUE,
  autodismiss = FALSE,
  class = "mx-auto"
)
```

## Arguments

|                                                           |                                                                                                                                                                                                                                                                                                                                                             |
|-----------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [`...`]{#audio_spinner_dotdotdot}                         | Additional attributes for the spinner, to be added directly to the `⁠<audio-spinner>⁠`{style="white-space: pre;"} element.                                                                                                                                                                                                                                    |
| [`src`]{#audio_spinner_src}                               | The source URL or URI for the audio file. This should be used for remote resources or data URIs. If provided, this takes precedence over `con`.                                                                                                                                                                                                             |
| [`con`]{#audio_spinner_con}                               | An optional connection object or file path for local audio files. This is ignored if `src` is provided. Use this for reading local files securely.                                                                                                                                                                                                          |
| [`rpm`]{#audio_spinner_rpm}                               | The speed of the spinner, in clockwise revolutions per minute. Default is 10 RPM. Use 0 to disable rotation, or a negative value to rotate counter-clockwise.                                                                                                                                                                                               |
| [`gap`]{#audio_spinner_gap}                               | The gap between the blades of the spinner, in radians. Default is pi/5, or 36°.                                                                                                                                                                                                                                                                             |
| [`stroke`]{#audio_spinner_stroke}                         | The stroke thickness of the individual arcs that make up each blade of the spinner, in pixels. Default is 2.5.                                                                                                                                                                                                                                              |
| [`min_radius`]{#audio_spinner_min_radius}                 | The radius of the spinner when there is only silence, in pixels. Default is 30.                                                                                                                                                                                                                                                                             |
| [`radius_compression`]{#audio_spinner_radius_compression} | The raw `⁠[-1, 1]⁠`{style="white-space: pre;"} amplitude of the audio is compressed using `x^radius_compression` to make the spinner more responsive to quiet sounds. Default is 0.8. Set to 1.0 to disable compression. (Note that this only affects the visualization, not the audio playback.)                                                             |
| [`radius_overscan`]{#audio_spinner_radius_overscan}       | Use this parameter to set the maximum possible radius of the spinner, relative to the width/height of the container. Default is 1.1, meaning the spinner radius will be scaled such that at maximum amplitude, it will be 10% larger than the container (the spinner blades will be clipped). Use larger values if you\'re expecting generally quiet audio. |
| [`steps`]{#audio_spinner_steps}                           | The number of concentric arcs that make up each blade of the spinner, not including the central circle. Default is 2.                                                                                                                                                                                                                                       |
| [`blades`]{#audio_spinner_blades}                         | The number of blades in the spinner. Default is 3. Set to 0 to use concentric circles instead of blades.                                                                                                                                                                                                                                                    |
| [`width`]{#audio_spinner_width}                           | The width of the spinner in CSS units. Default is \"125px\".                                                                                                                                                                                                                                                                                                |
| [`height`]{#audio_spinner_height}                         | The height of the spinner in CSS units. Default is \"125px\".                                                                                                                                                                                                                                                                                               |
| [`autoplay`]{#audio_spinner_autoplay}                     | Whether to autoplay the audio. Default is TRUE. Note that many browsers will not allow autoplaying audio without user interaction; if autoplay fails, the spinner will show a tooltip instructing the user to tap or click to start the audio.                                                                                                              |
| [`autodismiss`]{#audio_spinner_autodismiss}               | Whether to remove the spinner after the audio finishes playing. Default is FALSE.                                                                                                                                                                                                                                                                           |
| [`class`]{#audio_spinner_class}                           | The class of the spinner. Default is \"mx-auto\" which horizontally centers the element inside its container (assuming Bootstrap is loaded).                                                                                                                                                                                                                |

## Value

An HTML tag object representing the audio spinner.

## Examples

``` R
# Using a URL
audio_spinner(src = "https://example.com/audio.mp3", rpm = 15, width = "200px", height = "200px")

# Using a local file
audio_spinner(con = "path/to/local/audio.mp3", rpm = 20, width = "150px", height = "150px")
```
