---
title: '`input_video_clip`'
subtitle: |-
  A video clip input control that records short videos from
  webcam

---

## Description

A video clip input control that records short videos from webcam

## Usage

``` R
input_video_clip(
  inputId,
  reset_on_record = TRUE,
  mime_type = NULL,
  video_bits_per_second = NULL,
  audio_bits_per_second = NULL,
  ...
)
```

## Arguments

|                                                                    |                                                                                                                                                                                                                                                              |
|--------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [`inputId`]{#input_video_clip_inputid}                             | The input slot that will be used to access the value.                                                                                                                                                                                                        |
| [`reset_on_record`]{#input_video_clip_reset_on_record}             | Whether to reset the video clip input value when recording starts. If TRUE, the video clip input value will become NULL at the moment the Record button is pressed; if FALSE, the value will not change until the user stops recording. Default is TRUE.     |
| [`mime_type`]{#input_video_clip_mime_type}                         | The MIME type of the video clip to record. By default, this is NULL, which means the browser will choose a suitable MIME type for video recording. Common MIME types include \'video/webm\' and \'video/x-matroska\'.                                        |
| [`video_bits_per_second`]{#input_video_clip_video_bits_per_second} | The target video bitrate in bits per second. By default, this is NULL, which means the browser will choose a suitable bitrate for video recording (according to the spec, 2,500,000). This is only a suggestion; the browser may choose a different bitrate. |
| [`audio_bits_per_second`]{#input_video_clip_audio_bits_per_second} | The target audio bitrate in bits per second. By default, this is NULL, which means the browser will choose a suitable bitrate for audio recording. This is only a suggestion; the browser may choose a different bitrate.                                    |
| [`...`]{#input_video_clip_dotdotdot}                               | Additional parameters to pass to the underlying HTML tag.                                                                                                                                                                                                    |

## Value

A video clip input control that can be added to a UI definition.
